php artisan make:model TipoFuncionario
php artisan make:model EstadoFuncionario
php artisan make:model Area
php artisan make:model Especialidad
php artisan make:model EspecialidadArea
php artisan make:model Prevision
php artisan make:model Funcionario
php artisan make:model Paciente
php artisan make:model EstadoEpicrisis
php artisan make:model Epicrisis
php artisan make:model Procedimiento
php artisan make:model Antecedente
php artisan make:model Diagnostico
php artisan make:model MedicamentoSala
php artisan make:model Receta
php artisan make:model ComentarioEpicrisis
