# -*- mode: ruby -*-
# vi: set ft=ruby :
# Dependencias
# vagrant plugin install vagrant-hosts
# vagrant plugin install vagrant-cachier
#####
# Definición de ambientes laravel para proyecto Arq. Software
####

Vagrant.configure("2") do |config|

  config.vm.box = "laravel/homestead"

  nodes = {
  :frontend01   => {:host => 'as-frontend01',   :ip => '192.168.33.10', :dir => "Negocio",   :port => 8080},
  :backend01    => {:host => 'as-backend01',    :ip => '192.168.33.11', :dir => "Servicios", :port => 8081},
  :db01         => {:host => 'as-db01', :ip => '192.168.33.12'},
  }

  nodes.each do |name, options|
    config.vm.define name do |node|
      node.vm.provision :hot do |provisioner|
        provisioner.autoconfigure = false
        provisioner.add_host "#{options[:ip]}", "#{options[:node]}"
      end
      node.vm.network :private_network, ip: options[:ip]
      node.vm.hostname = "#{options[:hostname]}"
      node.vm.synced_folder "#{options[:dir]}", "/var/www/html/arq_soft", type: '9p'
      node.vm.network "forwarded_port", guest: 80, host: options[:port]
      if options[:host].include? "backend"
        node.vm.provision "shell", path: "./provision/backend.sh"
      elsif options[:host].include? "frontend"
        node.vm.provision "shell", path: "./provision/frontend.sh"
      end
    end
  end
end
